[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "Scatter"
version = "0.1.0"
description = "A simple tool for generating scatterplots."
requires-python = ">=3.13"
dependencies = [
    "pyside6",
    "matplotlib",
    "scipy",
    "numpy"
]

[tool.setuptools.packages.find]
include = ["Scatter*"]

[tool.setuptools.package-data]
Scatter = ["resources/views/*.ui"]